### ISSUE TITLE
Are multiline schema hints possible?

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/tutorials#70]
Hey guys, I suspect the parser enforces use of `#` but just double checking! 

```python
"""
schema:
*, col3:int
"""
def make_new_col(df: pd.DataFrame) -> pd.DataFrame:
    df['col3'] = df['col1'] + df['col2']
    return df 
```

> `One of the limitations of the schema hint is that linters often complain if there is a very long schema (past 70 or 80 characters).`

**Comment by kvnkho** [comment]
The short answer is that multi-line schema hints are not supported. This is because you can have non-Fugue related comments in your function. 
```python
# schema: *, col3:int
# other comments
def make_new_col(df: pd.DataFrame) -> pd.DataFrame:
    df['col3'] = df['col1'] + df['col2']
    return df 
```

This makes it hard to guess where the schema would end if it were multiline. It can likely be done if there are many users requesting for it.

**Comment by rdmolony** [comment]
Thanks Kevin
