### ISSUE TITLE
Link to illustration of join theory in beginner/joins.ipynb

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/tutorials#72]
Instead of ...

> Most joins should be familiar to users so this section will just be about providing examples how to use them in Fugue.

... perhaps we should link to a good resource on joins?

---

Options on a quick search:
- SQL: 
  - https://sqlbolt.com/lesson/select_queries_with_joins
  - https://www.w3schools.com/sql/sql_join.asp
- pandas: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
- spark: https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-join.html

**Comment by kvnkho** [comment]
Great idea! Fugue does also have some joins that users may not be used to like the anti-join.

**Comment by rdmolony** [comment]
Thanks Kevin, do you have any preference on including one particular source or multiple?  The linked sources are just illustrative.  Spark looks like the only one to reference anti-joins but it doesn't have any nice venn diagram illustrations

**Comment by kvnkho** [comment]
We'd likely need to make our own diagrams in the future to be comprehensive and consistent with the naming Fugue uses. It seems like a mess right if we link multiple ones? Maybe create a new issue to have diagrams?

**Comment by rdmolony** [comment]
Agreed, it shouldn't be too much work to make a few circles 😄
