### ISSUE TITLE
Add section 10 minutes to fugue

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/tutorials#74]
Similar to [10 minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html)  where you can learn just enough syntax to get started

**Comment by kvnkho** [comment]
This is a good idea. We should collaborate on this if you want :)

**Comment by rdmolony** [comment]
Sounds good, perhaps my incompetence will actually be an advantage on this one :)

**Comment by kvnkho** [comment]
We added 2 10 minutes sections now. 10 minutes to Fugue and 10 minutes to FugueSQL inspired by this issue 😃

**Comment by rdmolony** [comment]
Looks great Kevin ;)
